### ISSUE TITLE
เม้นแรก

### ISSUE THREAD

**Issue by timeimim** [wannaporn/Internship#1]
Hello World

**Comment by mmiclub** [comment]
ดีครับ อิอิ

**Comment by timeimim** [comment]
:pray: สวัสดีครับ ชื่อคุณากร อัชชะ เรียกสั้นๆว่า "ไทม์"  
.
:fire: มาจาก ม.ศิลปากร มาฝึกด้านโปรแกรมมิ่ง ยินดีที่ได้รู้จักพี่ๆเพื่อนๆทุกคนครับ 
.
.
:point_right: **ความถนัด** : design html css php 
:point_right: **ความสามารถ** : นอนดึกได้ งานไม่เสร็จไม่นอน ถ้าได้ทำจริงๆแล้วจะทำไม่หยุด
.
:sparkling_heart: **Facebook ส่วนตัว** : Times Acha
